sudo: required

language: python
python:
  - "2.7"
cache: pip

services:
  - docker

before_install:
- docker build -t travel_stop_review_api .
- docker run travel_stop_review_api /bin/sh  -c "python -m unittest discover"

script:
- python -m unittest discover

# after_success:
# TODO: push it to repe